# Generated by Django 4.2.1 on 2023-05-14 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='ActivityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField()),
                ('guests', models.IntegerField(default=0)),
                ('income', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'ActivityDetails',
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Church',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('churchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.church')),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('churchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.church')),
                ('departments', models.ManyToManyField(to='app.department')),
            ],
            options={
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activitydetails')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.member')),
            ],
            options={
                'db_table': 'Sermon',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Offering', 'Offering'), ('Tithe', 'Tithe'), ('Project', 'Project'), ('Others', 'Others')], max_length=15)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('churchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.church')),
                ('memberId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.member')),
            ],
            options={
                'db_table': 'Seed',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(auto_now=True)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
            options={
                'db_table': 'Payroll',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('attendance', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('churchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.church')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.AddConstraint(
            model_name='church',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='Unique church'),
        ),
        migrations.AddField(
            model_name='activitydetails',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='churchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.church'),
        ),
    ]
