# Generated by Django 4.2.1 on 2023-05-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appointment_id_alter_bill_id_alter_cashier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(to='app.medicine'),
        ),
    ]
