# Generated by Django 4.2.1 on 2023-05-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_labresult_description_alter_labresult_labassistantid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Dave man', max_length=50),
            preserve_default=False,
        ),
    ]
